# Generated by Django 3.1 on 2020-08-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_reporting',
            name='period',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
